# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.08.19
_src_path: gh:scientific-python/cookie
backend: hatch
email: jean.elsner@tum.de
full_name: Jean Elsner
license: Apache
org: tum-robotics
project_name: garmi-parti
project_short_description: Teleoperation between Garmi and Parti
url: https://github.com/tum-robotics/garmi-parti
vcs: true
